[book]
authors = ["Emre Ergun"]
language = "en"
multilingual = false
src = "src"
title = "Rust Book - A Collection of Notes"

[output.html]
git-repository-url="https://github.com/emre-ergun/mdbook-rust"
no-section-label=true

[output.html.playground]
runnable = false
