[book]
authors = ["Emre Ergun"]
language = "en"
multilingual = false
src = "src"
title = "Rust Explained"

[output.html]
git-repository-url="https://github.com/emre-ergun/mdbook-rust"

[output.html.playground]
runnable = false